# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

unit_tests: &unit_tests
  steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    - run: yarn install

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    # run tests!
    - run: yarn test

version: 2
jobs:
  node-8:
    docker:
      - image: circleci/node:8.15.1
    <<: *unit_tests
  node-10:
    docker:
      - image: circleci/node:10
    <<: *unit_tests
  node-latest:
    docker:
      - image: circleci/node:latest
    <<: *unit_tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - node-8
      - node-10
      - node-latest
