name: Sync

on:
  push:
    branches:
      - master

jobs:
  sync:
    strategy:
      matrix:
        site:
          - https://cnpmjs.org
          - https://npm.taobao.org
        package:
          - cli
          - core
          - dev-server
          - inspector
          - preset-babel
          - preset-env
          - preset-react
          - preset-serve
          - preset-style
          - preset-vue
          - preset-web
    runs-on: macos-latest
    steps:
      - name: request
        run: curl -X PUT ${{ matrix.site }}/sync/@best-shot/${{ matrix.package }}?sync_upstream=true
